apps/authentication/urls.py
from django.urls import path
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

app_name = "authentication"
urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", LogoutView.as_view(), name="logout")
]

apps/chats/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from rest_framework.routers import DefaultRouter
from .api import MessageModelViewSet, UserModelViewSet

router = DefaultRouter()
router.register(r'message', MessageModelViewSet, basename='message-api')
router.register(r'user', UserModelViewSet, basename='user-api')
app_name = "chats"
urlpatterns = [
    path(r'api/v1/', include(router.urls)),

    # path('', login_required(
    # TemplateView.as_view(template_name='chats/chat.html')), name='home'),
    path('', TemplateView.as_view(template_name='chats/chat.html'), name='chatws'),
]

apps/dht11/urls.py
from os.path import abspath

from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

from apps.dht11 import views

router = DefaultRouter()  # router
router.register('list', views.DHT11ViewSet)  # router
app_name = "dht11"
urlpatterns = [
    path('api/', include(router.urls), name='rest_api'),  # router
    path('api/lates/', views.dht11_lates, name='lates'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', views.dht11, name='dht11'),
    path('to_xlsx/', views.dht11_to_xlsx, name='to_xlsx'),
    #path('graphql/', views.GraphQLView.as_view()),
]
'''
1.  urlpatterns += router.urls
2.  url(r'^', include(router.urls)),
3.  với không gian tên ứng dụng : 
    url(r'^api/', include((router.urls, 'dht11'))),
4.  Hoặc cả không gian tên ứng dụng và phiên bản:
    url(r'^api/', include((router.urls, 'dht11'), namespace='instance_name')),
'''

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.urls import path, include
from django.views.static import serve
from django.conf.urls.static import static

from graphene_django.views import GraphQLView
from graphql_playground.views import GraphQLPlaygroundView
from core.schema import schema
from django.views.decorators.csrf import csrf_exempt  # New library

urlpatterns = [
    path("", include("apps.home.urls")),  # add this
    path("", include("apps.authentication.urls")),  # add this
    path('admin/', admin.site.urls),
    path('api/', csrf_exempt(GraphQLView.as_view(graphiql=False, schema=schema))),
    path('graphql/', csrf_exempt(GraphQLPlaygroundView.as_view(endpoint="http://127.0.0.1:8000/api/"))),
    path("dht11/", include('apps.dht11.urls')),
    path('chats/', include('apps.chats.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/templates/includes/aside-settings.html
    <!-- Custom template | don't include it in your project! -->
    <div class="custom-template">
        <div class="title">Settings</div>
        <div class="custom-content">
            <div class="switcher">
                <div class="switch-block">
                    <h4>Logo Header</h4>
                    <div class="btnSwitch">
                        <button type="button" class="changeLogoHeaderColor" data-color="dark"></button>
                        <button type="button" class="selected changeLogoHeaderColor" data-color="blue"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="purple"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="light-blue"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="green"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="orange"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="red"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="white"></button>
                        <br/>
                        <button type="button" class="changeLogoHeaderColor" data-color="dark2"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="blue2"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="purple2"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="light-blue2"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="green2"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="orange2"></button>
                        <button type="button" class="changeLogoHeaderColor" data-color="red2"></button>
                    </div>
                </div>
                <div class="switch-block">
                    <h4>Navbar Header</h4>
                    <div class="btnSwitch">
                        <button type="button" class="changeTopBarColor" data-color="dark"></button>
                        <button type="button" class="changeTopBarColor" data-color="blue"></button>
                        <button type="button" class="changeTopBarColor" data-color="purple"></button>
                        <button type="button" class="changeTopBarColor" data-color="light-blue"></button>
                        <button type="button" class="changeTopBarColor" data-color="green"></button>
                        <button type="button" class="changeTopBarColor" data-color="orange"></button>
                        <button type="button" class="changeTopBarColor" data-color="red"></button>
                        <button type="button" class="changeTopBarColor" data-color="white"></button>
                        <br/>
                        <button type="button" class="changeTopBarColor" data-color="dark2"></button>
                        <button type="button" class="selected changeTopBarColor" data-color="blue2"></button>
                        <button type="button" class="changeTopBarColor" data-color="purple2"></button>
                        <button type="button" class="changeTopBarColor" data-color="light-blue2"></button>
                        <button type="button" class="changeTopBarColor" data-color="green2"></button>
                        <button type="button" class="changeTopBarColor" data-color="orange2"></button>
                        <button type="button" class="changeTopBarColor" data-color="red2"></button>
                    </div>
                </div>
                <div class="switch-block">
                    <h4>Sidebar</h4>
                    <div class="btnSwitch">
                        <button type="button" class="selected changeSideBarColor" data-color="white"></button>
                        <button type="button" class="changeSideBarColor" data-color="dark"></button>
                        <button type="button" class="changeSideBarColor" data-color="dark2"></button>
                    </div>
                </div>
                <div class="switch-block">
                    <h4>Background</h4>
                    <div class="btnSwitch">
                        <button type="button" class="changeBackgroundColor" data-color="bg2"></button>
                        <button type="button" class="changeBackgroundColor selected" data-color="bg1"></button>
                        <button type="button" class="changeBackgroundColor" data-color="bg3"></button>
                        <button type="button" class="changeBackgroundColor" data-color="dark"></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="custom-toggle">
            <i class="flaticon-settings"></i>
        </div>
    </div>
    <!-- End Custom template -->

core/templates/includes/footer.html
  <footer class="footer">
    <div class="container-fluid font-weight-bold">
      <nav class="pull-left">
        <ul class="nav">
          <li class="nav-item">
            <span class="font-weight-bold ml-1 text-muted">
              {% now "jS F Y H:i" %}
            </span>
          </li>
        </ul>
      </nav>
      <div class="copyright ml-auto">
        &copy; <a href="#top" class="text-muted">RQS RD CO</a>
      </div>				
    </div>
  </footer>

core/templates/includes/navigation.html
<div class="main-header">
    <!-- Logo Header -->
    <div class="logo-header" data-background-color="dark2">
        <a href="/" class="logo">
            <img src="/static/assets/img/logo.svg" alt="navbar brand" class="navbar-brand" style="width: 50px; height: 50px">
        </a>
        <button class="topbar-toggler more"><i class="fab fa-fulcrum"></i></button>
        <div class="nav-toggle">
            <button class="btn btn-toggle toggle-sidebar">
						<i class="icon-menu"></i>
					</button>
        </div>
    </div>
    <!-- End Logo Header -->

    <!-- Navbar Header -->
    <nav class="navbar navbar-header navbar-expand-lg" data-background-color="dark">



        <div class="container-fluid">

            <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">

                <li class="nav-item dropdown hidden-caret">
                    <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
                        <i class="fas fa-layer-group"></i>
                    </a>
                    <div class="dropdown-menu quick-actions quick-actions-info animated fadeIn">
                        <div class="quick-actions-header">
                            <span class="title mb-1">Quick Actions</span>
                        </div>
                        <div class="quick-actions-scroll scrollbar-outer">
                            <div class="quick-actions-items">
                                <div class="row m-0">
                                    {% if request.user.is_superuser %}
                                    <a class="col-6 col-md-3 p-0" href="{% url 'admin:index' %}">
                                        <div class="quick-actions-item">
                                            <i class="fas fa-users-cog"></i>
                                            <span class="text">Admin</span>
                                        </div>
                                    </a>
                                    <a class="col-6 col-md-3 p-0" href="{% url 'dht11:dht11' %}">
                                        <div class="quick-actions-item">
                                            <i class="fas fa-temperature-high"></i>
                                            <span class="text">DHT11</span>
                                        </div>
                                    </a>
                                    <a class="col-6 col-md-3 p-0" href="{% url 'chats:chatws' %}">
                                        <div class="quick-actions-item">
                                            <i class="fas fa-video"></i>
                                            <span class="text">Chat</span>
                                        </div>
                                    </a>
                                    {% else %}
                                    <a class="col-6 col-md-3 p-0" href="{% url 'chats:chatws' %}">
                                        <div class="quick-actions-item">
                                            <i class="fas fa-video"></i>
                                            <span class="text">Chat</span>
                                        </div>
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </li>

            </ul>
        </div>

        <div class="container-fluid">
            <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown hidden-caret">
                    <a class="btn btn-default" href={% url 'authentication:logout' %}>
                        <i class="fa fa-sign-out" aria-hidden="true"><span class="link-collapse">&nbsp;</span></i> Logout
                    </a>
                </li>
                {% else %}
                <li class="nav-item dropdown hidden-caret">

                    <a class="btn btn-default" href={% url 'authentication:login' %}>
                        <i class="fas fa-sign-in-alt" aria-hidden="true"><span class="link-collapse">&nbsp;</span>&nbsp;</i>Login
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>

    </nav>
    <!-- End Navbar -->

</div>

core/templates/includes/scripts.html
	<!--   Core JS Files   -->
	<script src="/static/assets/js/core/jquery.3.2.1.min.js"></script>
	<script src="/static/assets/js/core/popper.min.js"></script>
	<script src="/static/assets/js/core/bootstrap.min.js"></script>

	<!-- jQuery UI -->
	<script src="/static/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
	<script src="/static/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>

	<!-- jQuery Scrollbar -->
	<script src="/static/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>

	<!-- Chart JS -->
	<script src="/static/assets/js/plugin/chart.js/chart.min.js"></script>

	<!-- jQuery Sparkline -->
	<script src="/static/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>

	<!-- Chart Circle -->
	<script src="/static/assets/js/plugin/chart-circle/circles.min.js"></script>

	<!-- Datatables -->
	<script src="/static/assets/js/plugin/datatables/datatables.min.js"></script>

	<!-- Bootstrap Notify -->
	<script src="/static/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>

	<!-- jQuery Vector Maps -->
	<script src="/static/assets/js/plugin/jqvmap/jquery.vmap.min.js"></script>
	<script src="/static/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>

	<!-- Sweet Alert -->
	<script src="/static/assets/js/plugin/sweetalert/sweetalert.min.js"></script>

	<!-- Atlantis JS -->
	<script src="/static/assets/js/atlantis.min.js"></script>

	<script src="/static/assets/js/setting-demo.js"></script>
	<!-- Icons -->
    <script defer src="https://kit.fontawesome.com/189832a678.js" crossorigin="anonymous"></script>

core/templates/includes/sidenav.html
<!-- Sidebar -->
<div class="sidebar sidebar-style-2" data-background-color="dark2">
    <div class="sidebar-wrapper scrollbar scrollbar-inner">

        <div class="sidebar-content">
            <ul class="nav nav-primary">
                <li class="nav-item">
                    <a href="{% url 'chats:chatws' %}">
                        <i class="fas fa-video"></i>
                        <span class="sub-item">Chat</span>
                    </a>
                </li>
                {% if request.user.is_superuser %}
                <li class="nav-item">
                    <a href="{% url 'admin:index' %}">
                        <i class="fab fa-jedi-order"></i>
                        <span class="sub-item">Admin</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a data-toggle="collapse" href="#dashboard" class="collapsed" aria-expanded="false">
                        <i class="fab fa-gg"></i>
                        <p>ESP32</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="dashboard">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="{% url 'dht11:dht11' %}">
                                    <i class="fab fa-ravelry"></i>
                                    <span class="sub-item">DHT11</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                {% endif %}
            </ul>
        </div>

    </div>
</div>
<!-- End Sidebar -->