apps/authentication/urls.py
from django.urls import path
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

app_name = "authentication"
urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", LogoutView.as_view(), name="logout")
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.urls import path, include
from django.views.static import serve
from django.conf.urls.static import static

from graphene_django.views import GraphQLView
from graphql_playground.views import GraphQLPlaygroundView
from core.schema import schema
from django.views.decorators.csrf import csrf_exempt  # New library

urlpatterns = [
    path("", include("apps.home.urls")),  # add this
    path("", include("apps.authentication.urls")),  # add this
    path('admin/', admin.site.urls),
    path('api/', csrf_exempt(GraphQLView.as_view(graphiql=False, schema=schema))),
    path('graphql/', csrf_exempt(GraphQLPlaygroundView.as_view(endpoint="http://127.0.0.1:8000/api/"))),
    path("dht11/", include('apps.dht11.urls')),
    path('chats/', include('apps.chats.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/templates/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Login</h4>
            <ul class="breadcrumbs">
                <li class="nav-home">
                    <a href="#">
                        <i class="flaticon-home"></i>
                    </a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
                <li class="nav-item">
                    <a href="#">Authentication</a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
                <li class="nav-item">
                    <a href="#">Login</a>
                </li>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <span>Login</span>
                        </div>
                    </div>

                    <br />

                    <div class="row">
                        <div class="col-md-6 col-lg-4">

                        {% if msg %}
                            <p style="margin-left: 25px">
                                {{ msg | safe }}
                            </p>
                        {% else %}
                            <p style="margin-left: 25px">    
                                
                            </p>
                        {% endif %}

                        </div>
                    </div>

                    <form method="post" action="">

                        {% csrf_token %}

                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 col-lg-4">

                                    <div class="form-group">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="icon-user"></i>
                                                </span>
                                            </div>
                                            {{ form.username }}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="icon-lock"></i>
                                                </span>
                                            </div>
                                            {{ form.password }}
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="card-action">
                            <button type="submit" class="btn btn-success">Submit</button>
                            &nbsp; &nbsp;
                            <span>Not a member?</span> Please <a href={% url 'authentication:register' %} >Register</a>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

core/templates/accounts/register.html
{% extends "layouts/base.html" %}

{% block title %} Register {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Register</h4>
            <ul class="breadcrumbs">
                <li class="nav-home">
                    <a href="#">
                        <i class="flaticon-home"></i>
                    </a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
                <li class="nav-item">
                    <a href="#">Authentication</a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
                <li class="nav-item">
                    <a href="#">Register</a>
                </li>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">

                            <span>Register</span>

                        </div>
                    </div>

                    <br />

                    <div class="row">
                        <div class="col-md-6 col-lg-4">

                        {% if msg %}
                            <p style="margin-left: 25px">
                                {{ msg | safe }}
                            </p>
                        {% else %}
                            <p style="margin-left: 25px">
                            </p>
                        {% endif %}

                        </div>
                    </div>

                    {% if success %}
                    
                    <div class="row">
                        <div class="col-md-6 col-lg-4">

                            <p style="margin-left: 25px">
                                Please <a href={% url 'login' %} class="text-black text-small">authenticate</a> using the new account.
                            </p>

                        </div>
                    </div>

                    {% else %}

                        <form method="post" action="">

                            {% csrf_token %}

                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6 col-lg-4">

                                        <div class="form-group">
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="icon-user"></i>
                                                    </span>
                                                </div>
                                                {{ form.username }}
                                            </div>
                                        </div>
                                        <span class="text-danger">{{ form.username.errors }}</span>

                                        <div class="form-group">
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="icon-envelope"></i>
                                                    </span>
                                                </div>
                                                {{ form.email }}
                                            </div>
                                        </div>
                                        <span class="text-danger">{{ form.email.errors }}</span>

                                        <div class="form-group">
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="icon-lock"></i>
                                                    </span>
                                                </div>
                                                {{ form.password1 }}
                                            </div>
                                        </div>
                                        <span class="text-danger">{{ form.password1.errors }}</span>

                                        <div class="form-group">
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">
                                                        <i class="icon-lock"></i>
                                                    </span>
                                                </div>
                                                {{ form.password2 }}
                                            </div>
                                        </div>
                                        <span class="text-danger">{{ form.password2.errors }}</span>

                                    </div>
                                </div>
                            </div>
                            <div class="card-action">
                                <button type="submit" class="btn btn-success">Submit</button>
                                &nbsp; &nbsp;
                                <span>Already have and account?</span> <a href={% url 'authentication:login' %} >Login</a>
                            </div>

                        </form>

                    {% endif %}

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}